courier/urls.py
from django.conf.urls import url
from django.urls import path,re_path

from courier import views
import courier
app_name = 'courier'

urlpatterns = [
  #  url(r'^CourierHomepage/$', views.homepage, name='CourierHomepage'),

    path('<str:courier_id>/CourierHomepage/', views.homepage, name='CourierHomepage'),

    path('<str:courier_id>/CourierPickuplists/', views.cpickuplist, name='CourierPickUpLists'),
 #   url(r'^CourierPickuplists/$', views.pickuplist, name='CourierPickUpLists'),

    path('<str:courier_id>/CourierStoreParcels/', views.storepage, name='CourierStoreParcels'),

    #url(r'^CourierStoreParcels/$', views.storepage, name='CourierStoreParcels'),



    path('<str:courier_id>/store/successful/<str:order_id>/', views.cpickup, name ='successfulpage'),

    path('<str:courier_id>/issue/<str:order_id>/', views.issue, name='issue'),
    path('<str:courier_id>/issue/<str:order_id>/issuereport/', views.issuereport, name='issuereport'),

    path('<str:courier_id>/CourierStoreParcels/storeinfo/', views.storeinfo, name='storeinfo'),

   # url(r' CourierStoreParcels/storeinfo', views.storeinfo, name="storeinfo"),
    path('<str:courier_id>/confirm/<str:order_id>/', views.confirmparcel, name ='confirmpage'),


    path('<str:courier_id>/noticeboard/', views.couriernotice, name ='couriernotice'),
]

epost/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from account import views
from customer.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^customer/', include('customer.urls')),
    url(r'^courier/', include('courier.urls')),
  #  url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^register/', views.register),
    url(r'^logout/', views.logout),
    url(r'^homepage/', views.index),

    #path('<str:career>/<str:user_id>/homepage/', views.index, name='index'),
]

courier/models.py
from django.db import models
import django.utils.timezone as timezone


class company(models.Model):
    company_id = models.CharField(max_length=10, primary_key=True, default='1')
    name = models.CharField(max_length=20, default='0')
    phone = models.CharField(max_length=20)
    price = models.CharField(max_length=20)
    address =models.CharField(max_length=200,default='')
class issue (models.Model):
    issue_id = models.CharField(max_length = 10, primary_key= True, default= '1')
    order_id = models.CharField(max_length=20, default= '0')
    title = models.CharField(max_length=20)
    content = models.CharField(max_length=200)
    date = models.DateTimeField(default = timezone.now)
    status = models.CharField(max_length=20, default= 'wait')

courier/views.py
from django.shortcuts import render, render_to_response, get_object_or_404,redirect
from account.models import *
from customer.models import order
from django.forms import fields
from django import forms
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from account.models import courier as Courier
from account.models import notice as noticeboard
from courier.models import issue as Issue
# Create your views here.


from django.http import HttpResponse


def homepage(request, courier_id):
    courier = Courier.objects.get(courier_id=courier_id)

    return render(request,'CourierHomepage.html',{'courier':courier})

def cpickuplist (request,courier_id):
    courier = Courier.objects.get(courier_id=courier_id)
    PickUpList = order.objects.filter(company_id=courier.company_id).filter(status='wait pick up')

    return render(request, 'CourierPickuplists.html', {'pickuplist': PickUpList,'courier':courier})

def cpickup( request, courier_id=None,order_id=None):
    courier = Courier.objects.get(courier_id=courier_id)

    package = order.objects.get(order_id =order_id)


    package.status = 'Picked Up'
    package.save()

    return render(request, 'SuccessfulPagec.html', {'package': package})

def issue( request, courier_id=None,order_id=None):

    courier = Courier.objects.get(courier_id=courier_id)

    return render(request, 'IssueReport.html', {'courier': courier,'order':order})
@csrf_exempt
def issuereport( request, order_id=None, courier_id = None):
        courier = Courier.objects.get(courier_id=courier_id)

        if request.POST:
            issue_title= request.POST.get("issue_title")
            issue_content= request.POST.get("issue_content")
            issuepackage = Issue(order_id=order_id,title=issue_title,content= issue_content)

            issuepackage.save()

            return redirect('http://127.0.0.1:8000/courier/1/CourierHomepage/')

def storepage( request, courier_id):



    courier = Courier.objects.get(courier_id=courier_id)

    return render(request, 'CourierStoreParcels.html', {'courier': courier,})


@csrf_exempt
def storeinfo (request,courier_id = None):
    courier = Courier.objects.get(courier_id=courier_id)

    if request.POST:
        parcels_trackid = request.POST.get("parcels_trackid")
        orderc= order.objects.get(track_id =parcels_trackid)

        storeinfo = order.objects.get(track_id=parcels_trackid)

        return render(request, 'CourierStoreInfo.html', {'storeinfo': storeinfo,'courier':courier,'order':orderc})

def confirmparcel( request, order_id=None,courier_id=None):


    confirmation = order.objects.get(order_id=order_id)
    confirmation.status = 'wait'
    confirmation.save()
    return render(request, 'ConfirmPage.html', {'confirmation': confirmation,'courier_id':courier_id,'order_id':order_id})

def couriernotice( request, order_id=None,courier_id = None):

    notice = noticeboard.objects.all()
    courier = Courier.objects.get(courier_id=courier_id)

    return render(request, 'CourierNoticeBoard.html',{'noticeboard': notice,'courier':courier})

courier/templates/ConfirmPage.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Confirmation</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">Confirm Infomation</p>
    <hr class="my-4">
    <p class="info">Please put {{confirmation.sender}}'s package in box {{confirmation.box_id}}</p>
      <br>
      <br>
    <a style=" position: absolute; left: 46%;" href="{% url 'courier:issuereport' confirmation.order_id %}">Report Issue</a>


     <input type="button" style="float :right" value="Continue" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/courier/{{courier_id}}/CourierStoreParcels'}" >
    <input type="button" style="float :right" value="back" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/courier/{{courier_id}}/CourierHomepage'}" >
    <button style="float :right" class="btn btn-outline-info">Log out</button>


</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

courier/templates/CourierHomepage.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Home Page</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">This is the homepage for couriers.</p>
  <hr class="my-4">
    <div id="demo" style="text-align:center;" >
     <input type="button" style="width:200px;height:40px; margin:5px" value="Pick Up" class="btn btn-outline-primary" onclick="{location.href='http://127.0.0.1:8000/courier/{{courier.courier_id}}/CourierPickuplists'}" >
     <input type="button" style="width:200px;height:40px;margin:5px" value="Store Parcels"class="btn btn-outline-primary" onclick="{location.href='http://127.0.0.1:8000/courier/{{courier.courier_id}}/CourierStoreParcels'}">
      <button type="button" style="width:200px;height:40px;margin:5px" class="btn btn-outline-primary" onclick="{location.href='http://127.0.0.1:8000/courier/{{courier.courier_id}}/noticeboard/'}" >Notice Board</button>
     <button type="button" style="width:200px;height:40px;margin:5px" class="btn btn-outline-primary">Feedback</button>
    </div>
      <br>
      <br>
      <br>
      <br>

    <button style="float :right" class="btn btn-outline-info">Log out</button>


</div>











    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

courier/templates/CourierNoticeBoard.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Notice Board</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">This is the NoticeBoard.</p>

    <hr class="my-4">


  <p> Title &emsp;&emsp;&emsp;  &emsp; content &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Time</p>

    {% for item in noticeboard %}
<div class="list" style="display: block">

    <p class="info">{{ item.title }} &emsp;&emsp;&emsp;&emsp;{{item.content}} &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{ item.publish}}

        &emsp;&emsp;



    </p>

    {{linebreaks }}
    <hr>
{% empty %}
<p>There are no packages for you.</p>

    {% endfor %}


</div>

    <button style="float :right" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/courier/{{courier.courier_id}}/CourierHomepage'}" >Return</button>


</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

courier/templates/CourierPickuplists.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>The list of Package</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">This is the your package lists.</p>

    <hr class="my-4">


  <p> Track id &emsp;&emsp;&emsp;  &emsp; Weight&emsp;&emsp;&emsp;&emsp; &emsp;Status&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Box</p>
    {% for item in pickuplist %}
<div class="list" style="display: block">

    <p class="info">{{ item.track_id }} &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{ item.weight}}KG&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{item.status}} &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{ item.box_id}}

        &emsp;&emsp;
        <a href="{% url 'courier:successfulpage'  courier_id=courier.courier_id order_id=item.order_id %}">pick up</a>



    </p>

    {{linebreaks }}
    <hr>
{% empty %}
<p>There are no packages for delivery .</p>

    {% endfor %}

    <input type="button" style="float :right" value="Back" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/courier/{{courier.courier_id}}/CourierHomepage'}" >
   <button style="float :right" class="btn btn-outline-info">Log out</button>


</div>

</div>





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

courier/templates/CourierStoreInfo.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Parcel information</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">
  <p class="lead">Parcels Detail Infomation</p>
    <div class="list" style="display: block">
    <p> Sender &emsp;&emsp;&emsp;  &emsp; Receiver&emsp;&emsp;&emsp;&emsp; Sender_Phone&emsp;&emsp;&emsp;&emsp;Receiver_Phone</p>
    <p class="info">{{ storeinfo.sender }}&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{ storeinfo.receiver}}&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; {{storeinfo.s_phone}}&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{ storeinfo.r_phone}}
    <p class="info">Sender address :{{storeinfo.s_address}}</p>
    <p class="info">Receiver address :{{storeinfo.r_address}}</p>

        <a href="{% url 'courier:confirmpage'  courier_id=courier.courier_id order_id=order.order_id %}">Confirm</a>
        <a style=" position: absolute; left: 46%;" href="{% url 'courier:issue' courier_id=courier.courier_id order_id=order.order_id  %}">Report Issue</a>

     <input type="button" style="float :right" value="Back" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/courier/{{courier.courier_id}}/CourierStoreParcels/'}" >
    <button style="float :right" class="btn btn-outline-info">Log out</button>


</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

courier/templates/CourierStoreParcels.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Store Parcels</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">
    <form class="form " action="storeinfo/{{order_id}}" method="post">
        {% csrf_token %}
        <p class="lead">Parcels Detail Infomation</p>
        <label class="">Track ID:</label> <label style="color: red;">*</label>
            <input type="trackid" name="parcels_trackid" class="form-control" placeholder="Trackid" required>
        <br>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Confirm</button>
        <input type="button" style="float :right" value="Back" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/courier/{{courier.courier_id}}/CourierHomepage/'}" >
        <button style="float :right" class="btn btn-outline-info">Log out</button>

    </form>
</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

courier/templates/SuccessfulPage.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Pick UP</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">Parcels Detail Infomation</p>
    <hr class="my-4">
    <p class="info">{{package.sender}}'s package is in box {{package.box_id}}</p>
    <p> Sender &emsp;&emsp;&emsp;  &emsp; Receiver&emsp;&emsp;&emsp;&emsp; Sender_Phone&emsp;&emsp;&emsp;&emsp;Receiver_Phone</p>
    <p class="info">{{ package.sender }}&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{ package.receiver}}&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; {{package.s_phone}}&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{ package.r_phone}}
    <p class="info">Sender address :{{package.s_address}}</p>
    <p class="info">Receiver address :{{package.r_address}}</p>
      <br>
      <br>
    <a style=" position: absolute; left: 46%;" href="{% url 'courier:issuereport' package.order_id  user.user_id%}">Report Issue</a>


     <input type="button" style="float :right" value="Back" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/courier/CourierPickuplists'}" >
    <button style="float :right" class="btn btn-outline-info">Log out</button>


</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>