customer/urls.py
from django.conf.urls import url, include
from django.urls import path,re_path
from customer import views
import  customer
app_name = 'customer'
urlpatterns = [

    path('<str:user_id>/homepage/', views.homepage, name='homepage'),
    path('<str:user_id>/lists/', views.pickuplist, name='PickUpList'),
  #  url(r'^lists/successful/(?P<order>\d+)$', views.pickup, name='successfulpage'),
    path('<str:user_id>/issuereport/<str:order_id>/', views.issuereport, name='issuereport'),
    path('<str:user_id>/lists/successful/<str:order_id>/', views.pickup, name ='successful'),
    path('<str:user_id>/noticeboard/', views.notice, name ='notice'),
    path('<str:user_id>/express/', views.send, name='express'),
]

epost/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from account import views
from customer.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^customer/', include('customer.urls')),
    url(r'^courier/', include('courier.urls')),
  #  url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^register/', views.register),
    url(r'^logout/', views.logout),
    url(r'^homepage/', views.index),

    #path('<str:career>/<str:user_id>/homepage/', views.index, name='index'),
]

customer/models.py
from django.db import models
from account.models import user

import django.utils.timezone as timezone
# Create your models here.


class order(models.Model):
   # models.IntegerField
    order_id = models.CharField(max_length = 10, primary_key= True, default= '1')
    date = models.DateTimeField(default = timezone.now)
    track_id = models.CharField(max_length=20)
    r_address = models.CharField(max_length=50)
    s_address = models.CharField(max_length=50)
    price = models.CharField(max_length=20)
    r_phone = models.CharField(max_length=50)
    s_phone = models.CharField(max_length=50)
    receiver = models.CharField(max_length=20)
   # sender = models.ForeignKey(user, to_field='user_id', on_delete=models.CASCADE)
    sender = models.CharField(max_length=20)
    weight = models.CharField(max_length=20)
    s_postcode = models.CharField(max_length=20)
    r_postcode = models.CharField(max_length=20)
    status = models.CharField(max_length=20)
    box_id = models.CharField(max_length=20)
    company_id = models.CharField(max_length=20)
    delivery_staff = models.CharField(max_length=20)




class issue (models.Model):
    issue_id = models.CharField(max_length = 10, primary_key= True, default= '1')
    order_id = models.CharField(max_length=20, default= '0')
    title = models.CharField(max_length=20)
    content = models.CharField(max_length=200)
    date = models.DateTimeField(default = timezone.now)
    user_id = models.ForeignKey(user, to_field='user_id', on_delete=models.CASCADE)
    status = models.CharField(max_length=20, default= 'wait')

customer/forms.py
from .models import issue
from django import forms
from courier.models import company

class IssueForm(forms.ModelForm):
	class Meta:
		model = issue
		fields = ('order_id', 'title','content','user_id')






class  OrderForm(forms.Form):

	#track_id = forms.CharField(max_length=20,label='track id')
	receiver = forms.CharField(max_length=20)
	receiver_address = forms.CharField(max_length=50,label='receiver address')
	r_postcode = forms.CharField(max_length=20, label='receiver postcode')
	receiver_phone = forms.CharField(max_length=20, label='receiver phone')

	sender = forms.CharField(max_length=20)
	sender_address = forms.CharField(max_length=50,label='sender address')
	s_postcode = forms.CharField(max_length=20, label='sender postcode')
	sender_phone = forms.CharField(max_length=20, label='sender phone')
	#price = forms.CharField(max_length=20, type='hidden')
	# sender = models.ForeignKey(user, to_field='user_id', on_delete=models.CASCADE)
	weight = forms.CharField(max_length=20, label='weight(KG)')
	#status = forms.CharField(max_length=20)
	company_id = forms.ChoiceField(label='Company', choices=((x.company_id, x.name+'  '+x.price+'$/KG') for x in company.objects.all()))
	#company_id = forms.ChoiceField()
	#choices=[('aupost','AU Post'),('dhl','DHL')]
	#delivery_staff = forms.CharField(max_length=20)

customer/views.py
from __future__ import  unicode_literals

from django.utils import timezone
from django.shortcuts import render, render_to_response

import account
import customer


# Create your views here.
from customer.models import order


def homepage(request):
    return render_to_response('homepage.html')

#页尾加个success  notice，url读取id没做
def issuereport(request):
    if request.method == "POST":
        contentinput = request.POST.get("issuescontent", None)
    #设置 order_id = 1
        issuesInput = models.issues.objects.create(
        order_id='1',
        title = '1',
        content = contentinput,
        date = timezone.now(),
        writer_id = '1',
        status = '1')
        issuesInput.save()
        return render(request, "issuereport.html")
    #显示存了什么
    return render(request, "issuereport.html")


    # issuesA = issues.objects.all()
    # content = {'issuesB':issuesA}
#profile  这个页面  应该是 表单显示信息，然后可更改，先做成插入的样子，后续再改
def profile(request):
    if request.method == "POST":
        user_id = request.POST.get("user_id", None)
        password = request.POST.get("password", None)
        name = request.POST.get("name", None)
        email = request.POST.get("email", None)
        phone = request.POST.get("phone", None)
        address = request.POST.get("address", None)
        gender = request.POST.get("gender", None)
        age = request.POST.get("age", None)
            # 设置 order_id = 1
        user = account.models.user.objects.get(user_id=user_id)
        user.user_id='1'
        user.account='1'
        user.password=password
        user.name=name
        user.type='1'
        user.email=email
        user.phone = phone
        user.address = address
        user.gender = gender
        user.age = age
        #这种save操作就相当于在update
        user.save()
        return render(request, "profile.html")
        # 显示存了什么   这里应该是依据id查找，不是select all
    user = account.models.user.objects.get(user_id="1")
    return render(request, "profile.html", {"user":user})

def rate(request):
    if request.method == "POST":
        level = request.POST.get("level", None)
        ratecontent = request.POST.get("ratecontent", None)
            # 设置 order_id = 1
        user = customer.models.rate.objects.create(
            rate_id='1',
            date=timezone.now(),
            level=level,
            content=ratecontent,
            order_id='1',
            writer_id='1',
            delivery_id = '1',)
        user.save()
        return render(request, "rate.html")
        # 显示存了什么
    return render(request, "rate.html")


def history(request):
    if request.method == "POST":
        delete_all = request.POST.get("delete_all", None)
        if delete_all == "Delete All":
            s_phone = request.POST.get("s_phone", None)
            customer.models.order.objects.filter(s_phone = s_phone).delete()
            return render(request, "history.html")
        else:
            order_id = request.POST.get("order_id", None)
        #应该加个status检查
            customer.models.order.objects.filter(order_id=order_id).delete()
            return render(request, "history.html")
        # 显示存了什么   这里应该是依据id查找，不是select all   order里缺少user_id
    orders = customer.models.order.objects.all()
    return render(request, "history.html", {"orders":orders})

customer/templates/IssueReport.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Report Issue</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">Report Issue</p>
    <hr class="my-4">
    <p class="info">Your package is in box {{package.box_id}}</p>


      <br>
      <br>
      <br>
      <br>
      <br>
      <br>


    <button style="float :right" class="btn btn-outline-info">Log out</button>


</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

customer/templates/NoticeBoard.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Notice Board</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">This is the NoticeBoard.</p>

    <hr class="my-4">


  <p> Title &emsp;&emsp;&emsp;  &emsp; content &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Time</p>

    {% for item in noticeboard %}
<div class="list" style="display: block">

    <p class="info">{{ item.title }} &emsp;&emsp;&emsp;&emsp;{{item.content}} &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{ item.publish}}

        &emsp;&emsp;



    </p>

    {{linebreaks }}
    <hr>
{% empty %}
<p>There are no packages for you.</p>

    {% endfor %}


</div>

    <button style="float :right" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/customer/{{user.user_id}}/homepage'}" >Return</button>


</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

customer/templates/OrderPage.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>New Order</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 850px; margin: auto;">

  <p class="lead">New Order</p>
        <hr class="my-4">
<form action="/customer/{{user.user_id}}/express/" method="post">
    {% csrf_token %}
    {{ orderform.as_p }}
    <input type="submit" value="Submit">
</form>



    <button style="float :right" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/customer/{{user.user_id}}/homepage'}" >Return</button>


</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

customer/templates/Payment.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Payment</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">This your new Order</p>
        <hr class="my-4">


   <p class="info">Your Tracking ID is: {{track_id}} &emsp;&emsp;</p>

    <p class="info">Price : {{price}}  </p>


 <button style="float:left" class="btn-outline-primary" onclick="{location.href='http://127.0.0.1:8000/customer/{{user.user_id}}/homepage'}" >Return</button>


<br>
    <br>
    <br>
    <br>


    <button style="float :right" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/customer/{{user.user_id}}/homepage'}" >Return</button>


</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

customer/templates/PickUpList.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>The list of Package</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">This is the your package lists.</p>

    <hr class="my-4">


  <p> Track id &emsp;&emsp;&emsp;  &emsp; Weight&emsp;&emsp;&emsp;&emsp; Status&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Box</p>

    {% for item in pickuplist %}
<div class="list" style="display: block">

    <p class="info">{{ item.track_id }} &emsp;&emsp;&emsp;&emsp;{{ item.weight}}KG&emsp;&emsp;&emsp;&emsp;&emsp;{{item.status}} &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{ item.box_id}}

        &emsp;&emsp;
        <a href="{% url 'customer:successful' user_id=user.user_id order_id=item.order_id %}">pick up</a>



    </p>

    {{linebreaks }}
    <hr>
{% empty %}
<p>There are no packages for you.</p>

    {% endfor %}


    <button style="float :right" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/customer/{{user.user_id}}/homepage'}" >Return</button>

</div>




</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

customer/templates/SuccessfulPage.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Pick UP</title>
  </head>
  <body>

<div class="jumbotron" style="width:600px;height: 450px; margin: auto;">

  <p class="lead">Congritulation!</p>
    <hr class="my-4">
    <p class="info">Your package is in box {{package.box_id}}</p>

      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    <a style=" position: absolute; left: 46%;" href="{% url 'customer:issuereport' user_id=user.user_id order_id=package.order_id %}">Report Issue</a>



    <button style="float :right" class="btn btn-outline-info" onclick="{location.href='http://127.0.0.1:8000/customer/{{user.user_id}}/homepage'}" >Return</button>


</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

customer/templates/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>History Order</title>
    <style>
        #out{
            border:1px solid #000000;
            width: 500px;
            overflow:auto;

        }
        div{
            width:2600px;
        }
        #hide{
        display: none;
    }
    </style>
</head>
<body>
<div>
    <div class="jumbotron" style="width:3400px;height: 500px; margin: auto;">
        <h1 class="display-4">Your history order</h1>
        <form action="/customer/{{user.user_id}}/history/" method="post">{% csrf_token %}
         {% for order in orders %}
                     <input tpye="hidden" id="hide" name = "order_id" value="{{order.order_id}}" >
         <text>date</text>
         <input tpye="text" name = "date" value="{{order.date}}" readonly>
         <text>weight</text>
         <input tpye="text" name = "weight" value="{{order.weight}}" readonly>
        <text>price</text>
         <input tpye="text" name = "price" value="{{order.price}}" readonly>
        <text>sender</text>
         <input tpye="text" name = "sender" value="{{order.sender}}" readonly>
        <text>sender phone</text>
         <input tpye="text" name = "s_phone" value="{{order.s_phone}}" readonly>
        <text>send address</text>
         <input tpye="text" name = "s_address" value="{{order.s_address}}" readonly>
        <text>send postcode</text>
         <input tpye="text" name = "s_postcode" value="{{order.s_postcode}}" readonly>
        <text>receiver</text>
         <input tpye="text" name = "receiver" value="{{order.receiver}}" readonly>
        <text>receiver phone</text>
         <input tpye="text" name = "r_phone" value="{{order.r_phone}}" readonly>
        <text>receiver address</text>
         <input tpye="text" name = "r_address" value="{{order.r_address}}" readonly>
        <text>receive postcode</text>
         <input tpye="text" name = "r_postcode" value="{{order.r_postcode}}" readonly>
        <!--这里应该有个判定，判定出是收件员还是发货员-->
        <text>service staff</text>
         <input tpye="text" name = "staff" value="{{order.delivery_staff}}" readonly>
        <input  style="float :right" class="btn btn-outline-info" type="submit" name="{{order.order_id}}" value ="Delete"/>

        <br>
             {% endfor %}
         <input style="float :left" class="btn btn-outline-info" type="submit" name="delete_all"  value ="Delete All"/>

    </form>
         <!--<input name="submit" type="submit" value ="submit"/>-->

    </div>
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

customer/templates/issuereport.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>IssueReport</title>
  </head>
  <body>
     <h1>Issue Report</h1>
     <h1 class="display-4">Do your have issues on your order?</h1>
     <p class="lead">If you have any issues about your using, you can input and submit the content.</p>
     <hr class="my-4">
     <form action="/customer/issuereport/" method="post">{% csrf_token %}
         <text>issue content</text>
         <input type="text" name ="issuescontent"/>
         <input name="submit" type="submit" value ="submit"/>
    </form>

    <ul>{% block succeed %}
       <p></p>
    {% endblock %}
    </ul>

</div>











    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>